In [ ]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np
import math
import h5py
import matplotlib.pyplot as plt
from tensorflow.python.framework import ops
from tensorflow import keras

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# navigate to CS 230 Project folder. This might have a different path depending on user
#os.chdir("/content/drive/MyDrive/Classes/CS 230 Project/Data") # Fletch's path
os.chdir("/content/drive/MyDrive/CS 230 Project/Data") # Kopal's path

In [ ]:
rmse_data = np.load('rmse_results.npy')

In [ ]:
rmse_data

array([[[[7.94477527e-01, 4.47620234e-01, 5.18899624e-01,
          4.99195539e-01, 7.08252710e-01, 2.32530684e-01,
          5.02077211e-01, 8.79202557e-01],
         [7.11161637e-04, 8.93174558e-02, 2.02075032e-01,
          4.01744997e-02, 1.00175669e-01, 2.05583054e-03,
          2.99586586e-01, 1.22869646e-01],
         [3.71098591e-04, 4.74719403e-02, 1.72775181e-01,
          4.87163668e-02, 7.19697699e-02, 1.83785967e-03,
          2.72671915e-01, 9.47294718e-02]],

        [[7.03914211e-01, 5.90018951e-01, 8.49509116e-01,
          2.82001590e-01, 3.32527678e-01, 4.01100921e-01,
          7.03091101e-01, 2.84817573e-01],
         [3.44270875e-01, 8.86291712e-02, 2.04556072e-01,
          1.64248826e-01, 1.16191634e-01, 2.25270013e-01,
          2.85868020e-01, 4.42042792e-01],
         [7.30141801e-04, 5.29013199e-02, 1.83719471e-01,
          5.17903780e-02, 7.71635468e-02, 2.49297492e-03,
          2.65013982e-01, 9.94809942e-02]],

        [[3.48509256e-01, 1.73467695e-01, 

In [ ]:
np.shape(rmse_data)

(2, 3, 3, 8)

In [ ]:
np.mean(rmse_data, axis = 3)

array([[[0.57278201, 0.10712074, 0.08881795],
        [0.51837264, 0.23388468, 0.0916616 ],
        [0.27945843, 0.12579934, 0.08748436]],

       [[2.2111638 , 2.23645134, 2.1641548 ],
        [2.21551715, 2.209439  , 2.20996062],
        [2.2124466 , 2.20129883, 2.18238484]]])

In [ ]:
rmse_final = np.mean(rmse_data, axis = 3)

In [ ]:
first_dim_mapping = {0: 'Demand_Ratio', 1: 'Original'}
second_dim_mapping = {0: 'All_weather', 1: 'Gilroy', 2: 'No_weather'}
third_dim_mapping = {0: '24-LSTM', 1: '48-GRU', 2: '72-LSTM'}
for i in range(2):
  for j in range(3):
    for k in range(3):
      #print ("model_" + str(i) + str(j) + str(k) + "is" + str(rmse_final[i,j,k]))
      print (first_dim_mapping[i], ",", second_dim_mapping[j], ",", third_dim_mapping[k], " ", rmse_final[i,j,k])

Demand_Ratio , All_weather , 24-LSTM   0.5727820108674091
Demand_Ratio , All_weather , 24-GRU   0.10712073527029854
Demand_Ratio , All_weather , 72-LSTM   0.08881795036359541
Demand_Ratio , Gilroy , 24-LSTM   0.5183726425233639
Demand_Ratio , Gilroy , 24-GRU   0.23388467550448588
Demand_Ratio , Gilroy , 72-LSTM   0.0916616011166122
Demand_Ratio , No_weather , 24-LSTM   0.2794584311162833
Demand_Ratio , No_weather , 24-GRU   0.1257993363347986
Demand_Ratio , No_weather , 72-LSTM   0.08748435575773908
Original , All_weather , 24-LSTM   2.2111638010182544
Original , All_weather , 24-GRU   2.2364513382904603
Original , All_weather , 72-LSTM   2.1641547960411245
Original , Gilroy , 24-LSTM   2.2155171534191487
Original , Gilroy , 24-GRU   2.209438997545966
Original , Gilroy , 72-LSTM   2.209960616088644
Original , No_weather , 24-LSTM   2.2124466010874007
Original , No_weather , 24-GRU   2.2012988344807405
Original , No_weather , 72-LSTM   2.182384839553689


In [ ]:
rmse_data 

array([[[[7.94477527e-01, 4.47620234e-01, 5.18899624e-01,
          4.99195539e-01, 7.08252710e-01, 2.32530684e-01,
          5.02077211e-01, 8.79202557e-01],
         [7.11161637e-04, 8.93174558e-02, 2.02075032e-01,
          4.01744997e-02, 1.00175669e-01, 2.05583054e-03,
          2.99586586e-01, 1.22869646e-01],
         [3.71098591e-04, 4.74719403e-02, 1.72775181e-01,
          4.87163668e-02, 7.19697699e-02, 1.83785967e-03,
          2.72671915e-01, 9.47294718e-02]],

        [[7.03914211e-01, 5.90018951e-01, 8.49509116e-01,
          2.82001590e-01, 3.32527678e-01, 4.01100921e-01,
          7.03091101e-01, 2.84817573e-01],
         [3.44270875e-01, 8.86291712e-02, 2.04556072e-01,
          1.64248826e-01, 1.16191634e-01, 2.25270013e-01,
          2.85868020e-01, 4.42042792e-01],
         [7.30141801e-04, 5.29013199e-02, 1.83719471e-01,
          5.17903780e-02, 7.71635468e-02, 2.49297492e-03,
          2.65013982e-01, 9.94809942e-02]],

        [[3.48509256e-01, 1.73467695e-01, 

In [ ]:
class_map = {'coal': 0, 'hydro': 1, 'ng ': 2, 'nuclear': 3, 'other': 4, 'petrol': 5, 'solar': 6, 'wind': 7}
class_wise_results = {}
# coal = []
# hydro = []
# ng =[]
# nuclear=[]
# other=[]
# petrol=[]
# solar=[]
# wind=[]
for cls, v in class_map.items():
  class_wise_results[cls] = list()
  for i in range(2):
    for j in range(3):
      for k in range(3):
          class_wise_results[cls].append(rmse_data[i, j, k, class_map[cls]])
        # hydro.append(rmse_data[i,j,k,1])
        # ng.append(rmse_data[i,j,k,2])
        # nuclear.append(rmse_data[i,j,k,3])
        # other.append(rmse_data[i,j,k,4])
        # petrol.append(rmse_data[i,j,k,5])
        # solar.append(rmse_data[i,j,k,6])
        # wind.append(rmse_data[i,j,k,7])

flat_idx_to_tuple_list = []
for i in range(2):
  for j in range(3):
    for k in range(3):
      flat_idx_to_tuple_list.append((first_dim_mapping[i], second_dim_mapping[j], third_dim_mapping[k]))

for cls, v in class_map.items():
  min_index = class_wise_results[cls].index(min(class_wise_results[cls]))
  print(cls, min_index, flat_idx_to_tuple_list[min_index])

coal 2 ('Demand_Ratio', 'All_weather', '72-LSTM')
hydro 8 ('Demand_Ratio', 'No_weather', '72-LSTM')
ng  8 ('Demand_Ratio', 'No_weather', '72-LSTM')
nuclear 1 ('Demand_Ratio', 'All_weather', '24-GRU')
other 8 ('Demand_Ratio', 'No_weather', '72-LSTM')
petrol 2 ('Demand_Ratio', 'All_weather', '72-LSTM')
solar 5 ('Demand_Ratio', 'Gilroy', '72-LSTM')
wind 8 ('Demand_Ratio', 'No_weather', '72-LSTM')


In [ ]:
# min_coal = coal.index(min(coal))
# min_hydro = hydro.index(min(hydro))
# min_ng = ng.index(min(ng))
# min_nuclear = nuclear.index(min(nuclear))
# min_other = other.index(min(other))
# min_petrol = petrol.index(min(petrol))
# min_solar = solar.index(min(solar))
# min_wind = wind.index(min(wind))
# print (min_coal, min_hydro, min_ng, min_nuclear, min_other, min_petrol, min_solar, min_wind)

2 8 8 1 8 2 5 8
